# Generated by Django 4.1.5 on 2023-03-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client_Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Contact_Number', models.IntegerField()),
                ('Appointment_Date', models.DateField()),
                ('Appointment_Time', models.TimeField()),
            ],
            options={
                'db_table': 'BookAppointment',
            },
        ),
        migrations.CreateModel(
            name='Client_Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientname', models.CharField(max_length=40)),
                ('clientfeedback', models.CharField(max_length=120)),
                ('clientage', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('contactno', models.IntegerField()),
            ],
            options={
                'db_table': 'Client',
            },
        ),
    ]
